"""SSRL semantic model — the stable, auditable fact/hypothesis abstraction.

Classes of knowledge (docs/concepts.md):
- FACTS      : derived structurally, confidence 1.0, never probabilistic (FR-3, FR-4).
- HYPOTHESES : inferred, carry confidence in [0,1) and explicit evidence (FR-3, FR-4).

Node/edge taxonomy follows docs/projections/graph.md (candidate schema),
kept projection-agnostic per architecture invariant D4.
"""

import uuid

# --- taxonomy -----------------------------------------------------------------

NODE_TYPES = {
    # structural (facts)
    "Repository", "Module", "Class", "Function", "Method", "Import",
    # semantic (hypotheses, generated by enrichment)
    "DomainConcept", "Flow", "Intent", "Service",
}

EDGE_TYPES = {
    # structural (facts)
    "CONTAINS", "IMPORTS", "CALLS",
    # semantic (hypotheses)
    "PARTICIPATES_IN",   # module/function -> Flow
    "SUPPORTS_INTENT",   # module/function -> Intent
    "RELATED_TO",        # fallback semantic relation
}

# node types that are always facts
STRUCTURAL_NODES = {"Repository", "Module", "Class", "Function", "Method"}
STRUCTURAL_EDGES = {"CONTAINS", "IMPORTS", "CALLS"}


def new_id(kind, *parts):
    """Deterministic node id, e.g. new_id('func', 'pkg.mod', 'run')."""
    return f"{kind}::{'::'.join(p for p in parts if p)}"


def edge_id():
    """Ephemeral edge id (edge identity is source+target+relationship)."""
    return f"e:{uuid.uuid4().hex[:12]}"


def make_edge(source, target, relationship, evidence=None, metadata=None, confidence=1.0):
    """Build an edge dict. `source`/`target` are node ids."""
    return {
        "id": edge_id(),
        "source": source,
        "target": target,
        "relationship": relationship,
        "confidence": confidence,
        "evidence": evidence or [],
        "metadata": metadata or {},
    }


def is_fact(kind_or_conf):
    """True for facts (structural kind or confidence==1.0)."""
    if isinstance(kind_or_conf, float) or isinstance(kind_or_conf, int):
        return kind_or_conf == 1.0
    return kind_or_conf in STRUCTURAL_NODES or kind_or_conf in STRUCTURAL_EDGES